name       : svtplay-dl
version    : '2.1'
release    : 5
source     :
    - git|https://github.com/spaam/svtplay-dl.git : d33186e54e436ebb1537e5baf67758e3bd3bf076
homepage   : https://svtplay-dl.se/
license    : MIT
component  : network.download
summary    : Small command-line program to download videos from some streaming sites
description: |
    svtplay-dl is an open source command-line program written in python. You can quickly download published videos from various sites to your local computer.
rundeps    :
    - ffmpeg
    - python-cryptography
    - python-pysocks
    - python-requests
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
