name       : svtplay-dl
version    : '3.7'
release    : 16
source     :
    - https://github.com/spaam/svtplay-dl/archive/refs/tags/3.7.tar.gz : 34c99bd9061c0b1563974656f95e5ac1969f0675998221bc836bec0ff7b25e0c
homepage   : https://svtplay-dl.se/
license    : MIT
component  : network.download
summary    : Small command-line program to download videos from some streaming sites
description: |
    svtplay-dl is an open source command-line program written in python. You can quickly download published videos from various sites to your local computer.
rundeps    :
    - ffmpeg
    - python-cryptography
    - python-pysocks
    - python-requests
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
