name       : svtplay-dl
version    : 1.9.7
release    : 1
source     :
    - https://github.com/spaam/svtplay-dl/archive/1.9.7.tar.gz : 0fe9cf2b5736a5d9b1687a42593cc2814ba9c7b1035520b51b1591324e08a445
license    : MIT
component  : network.download
summary    : Small command-line program to download videos from Swedish websites.
description: |
    Small command-line program to download videos from Swedish websites.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(librtmp)
    - python-setuptools
    - python-requests
    - python-pysocks
    - pycrypto
    - ffmpeg
rundeps    :
    - ffmpeg
build      : |
    %python3_setup
install    : |
    %python3_install
