name       : svtplay-dl
version    : 1.9.10
release    : 2
source     :
    - https://github.com/spaam/svtplay-dl/archive/1.9.10.tar.gz : 0bf9e4593d2d6b7d75f28fdb068a2f7a4ccf1e1d43b758652c759a3c4a3ad3ed
license    : MIT
component  : network.download
summary    : Small command-line program to download videos from Swedish websites.
description: |
    Small command-line program to download videos from Swedish websites.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(librtmp)
    - python-setuptools
    - python-requests
    - python-pysocks
    - pycrypto
    - ffmpeg
rundeps    :
    - ffmpeg
build      : |
    %python3_setup
install    : |
    %python3_install
