name       : svtplay-dl
version    : '2.6'
release    : 12
source     :
    - https://github.com/spaam/svtplay-dl/archive/2.6.tar.gz : e9b7675b5224169107dcb7d7c1cc86741c3eceddd2c15f6c30a4d65c89b643fd
homepage   : https://svtplay-dl.se/
license    : MIT
component  : network.download
summary    : Small command-line program to download videos from some streaming sites
description: |
    svtplay-dl is an open source command-line program written in python. You can quickly download published videos from various sites to your local computer.
rundeps    :
    - ffmpeg
    - python-cryptography
    - python-pysocks
    - python-requests
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
