name       : svtplay-dl
version    : '2.0'
release    : 3
source     :
    - https://github.com/spaam/svtplay-dl/archive/2.0.tar.gz : d392381f5af71976998b0586a8616aa108828b263da2d483ab6682fe66d25016
license    : MIT
component  : network.download
summary    : Small command-line program to download videos from some streaming sites
description: |
    svtplay-dl is an open source command-line program written in python. You can quickly download published videos from various sites to your local computer.
rundeps    :
    - ffmpeg
    - python-pysocks
    - python-requests
    - python3-pycryptodome
    - pyyaml
    - rtmpdump
build      : |
    %python3_setup
install    : |
    %python3_install
